# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Cxfo01YVLOgvJf6HwRNQsUUvBAytVp7R
"""

# streamlit_app.py
import streamlit as st
import pandas as pd
import yfinance as yf
import plotly.graph_objects as go
from sklearn.ensemble import RandomForestClassifier
import random

st.set_page_config(page_title="AI vs Human 交易遊戲", layout="wide")

# ---------- 技術指標 ----------
def add_kdj(df, n=9, k_period=3, d_period=3):
    low_min = df['Low'].rolling(n, min_periods=1).min()
    high_max = df['High'].rolling(n, min_periods=1).max()
    rsv = (df['Close'] - low_min) / (high_max - low_min + 1e-9) * 100
    df['K'] = rsv.ewm(span=k_period, adjust=False).mean()
    df['D'] = df['K'].ewm(span=d_period, adjust=False).mean()
    df['J'] = 3*df['K'] - 2*df['D']
    return df

def add_rsi(df, period=6):
    delta = df['Close'].diff()
    gain = delta.clip(lower=0)
    loss = -delta.clip(upper=0)
    avg_gain = gain.rolling(period, min_periods=1).mean()
    avg_loss = loss.rolling(period, min_periods=1).mean()
    rs = avg_gain / (avg_loss + 1e-10)
    df['RSI'] = 100 - 100/(1+rs)
    return df

def add_macd(df):
    df['EMA_short'] = df['Close'].ewm(span=12, adjust=False).mean()
    df['EMA_long'] = df['Close'].ewm(span=26, adjust=False).mean()
    df['MACD'] = df['EMA_short'] - df['EMA_long']
    df['MACD_signal'] = df['MACD'].ewm(span=9, adjust=False).mean()
    df['MACD_hist'] = df['MACD'] - df['MACD_signal']
    return df

# ---------- 抓資料 ----------
@st.cache_data
def fetch_data(ticker="ETH-USD", period="60d", interval="5m"):
    df = yf.download(ticker, period=period, interval=interval)
    if isinstance(df.columns, pd.MultiIndex):
        df.columns = df.columns.droplevel(1)
    df = add_kdj(df)
    df = add_rsi(df)
    df = add_macd(df)
    df.dropna(inplace=True)
    return df

# ---------- 訓練 AI ----------
def train_ai(train_df):
    df = train_df.copy()
    df['target'] = (df['Close'].shift(-1) > df['Close']).astype(int)
    df.dropna(subset=['target'], inplace=True)
    feats = ["K","D","J","RSI","MACD","MACD_signal","MACD_hist"]
    X, y = df[feats], df['target']
    model = RandomForestClassifier(n_estimators=80, random_state=42)
    model.fit(X, y)
    return model, feats

# ---------- 初始化遊戲 ----------
if "game_df" not in st.session_state:
    full_df = fetch_data()
    game_start_index = random.randint(0, len(full_df)-30)
    st.session_state.game_df = full_df.iloc[game_start_index:game_start_index+30].copy()
    train_df = pd.concat([full_df.iloc[:game_start_index], full_df.iloc[game_start_index+30:]])
    st.session_state.model, st.session_state.feats = train_ai(train_df)

    # 初始資產
    st.session_state.human_cash = 10000.0
    st.session_state.human_asset = 0.0
    st.session_state.ai_cash = 10000.0
    st.session_state.ai_asset = 0.0
    st.session_state.step = 20  # 前20根K線先展示
    st.session_state.countdown = 10
    st.session_state.game_started = False

st.title("💹 AI vs Human 交易遊戲 (ETH-USD)")

# ---------- 倒數計時 ----------
if not st.session_state.game_started:
    st.write(f"離遊戲開始還有 {st.session_state.countdown} 秒")
    start_game = st.button("立即開始遊戲 ⏩")
    if start_game or st.session_state.countdown <= 0:
        st.session_state.game_started = True
    else:
        st.session_state.countdown -= 1
        st.experimental_rerun()
else:
    st.write("遊戲開始！")

# ---------- 顯示K線 ----------
sub_df = st.session_state.game_df.iloc[:st.session_state.step+1]
fig = go.Figure(data=[go.Candlestick(
    x=sub_df.index,
    open=sub_df['Open'], high=sub_df['High'],
    low=sub_df['Low'], close=sub_df['Close']
)])
st.plotly_chart(fig, use_container_width=True)

# ---------- 玩家操作 ----------
col1, col2 = st.columns(2)
with col1:
    if st.button("買入 🟢"):
        current_price = st.session_state.game_df.iloc[st.session_state.step]['Close']
        if st.session_state.human_cash > 0:
            st.session_state.human_asset += st.session_state.human_cash / current_price
            st.session_state.human_cash = 0

with col2:
    if st.button("賣出 🔴"):
        current_price = st.session_state.game_df.iloc[st.session_state.step]['Close']
        if st.session_state.human_asset > 0:
            st.session_state.human_cash += st.session_state.human_asset * current_price
            st.session_state.human_asset = 0

# ---------- AI操作 ----------
current_price = st.session_state.game_df.iloc[st.session_state.step]['Close']
ai_feats = st.session_state.game_df[st.session_state.feats].iloc[st.session_state.step].to_frame().T
ai_pred = st.session_state.model.predict(ai_feats)[0]
if ai_pred==1 and st.session_state.ai_cash>0:
    st.session_state.ai_asset += st.session_state.ai_cash / current_price
    st.session_state.ai_cash = 0
elif ai_pred==0 and st.session_state.ai_asset>0:
    st.session_state.ai_cash += st.session_state.ai_asset * current_price
    st.session_state.ai_asset = 0

# ---------- 更新步數 ----------
if st.session_state.game_started:
    if st.session_state.step < len(st.session_state.game_df)-1:
        st.session_state.step += 1
        st.experimental_rerun()
    else:
        # 遊戲結束
        human_value = st.session_state.human_cash + st.session_state.human_asset * current_price
        ai_value = st.session_state.ai_cash + st.session_state.ai_asset * current_price
        winner = "人類" if human_value > ai_value else ("AI" if ai_value > human_value else "平手")
        st.success(f"遊戲結束！人類資產: {human_value:.2f}, AI資產: {ai_value:.2f}, 贏家: {winner}")

# ---------- 顯示玩家與AI資產 ----------
st.write(f"人類現金: {st.session_state.human_cash:.2f} | 人類資產: {st.session_state.human_asset:.6f}")
st.write(f"AI現金: {st.session_state.ai_cash:.2f} | AI資產: {st.session_state.ai_asset:.6f}")